HTTP/1.1 200 OK
X-Powered-By: Express
Content-Type: application/json; charset=utf-8
Content-Length: 60
ETag: W/"3c-qEHaeM6DRe0aMJO4S0XzPWhTaPI"
Date: Tue, 16 Jul 2024 11:52:35 GMT
Connection: close

{"id":7,"task":"Never gonna give you up","completion":false}