HTTP/1.1 200 OK
X-Powered-By: Express
Content-Type: application/json; charset=utf-8
Content-Length: 59
ETag: W/"3b-3QFVKL+b7y+0HezJgzl3AmZ/XlI"
Date: Tue, 16 Jul 2024 11:55:26 GMT
Connection: close

{"id":7,"task":"Never gonna give you up","completion":true}