GET http://localhost:3000/api/tasks

###

GET http://localhost:3000/api/tasks/3

###

POST http://localhost:3000/api/tasks HTTP/1.1
content-type: application/json

{
  "completion": false,
  "task": "Never gonna give you up"
}

###

PUT http://localhost:3000/api/tasks/7

###

DELETE http://localhost:3000/api/tasks/7